var app = getApp()  
Page({  
 data: {  
   movies:[  
  {url:'http://opgfoveg6.bkt.clouddn.com/swiper0'} ,  
  {url:'http://opgfoveg6.bkt.clouddn.com/swiper2'} ,  
  {url:'http://opgfoveg6.bkt.clouddn.com/swiper3'} ,  
  {url:'http://opgfoveg6.bkt.clouddn.com/swiper4'}   
  ],
  chahuaRankArray:[
          {
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/team001',    
          },
          {
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/team002'

          },
          {
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/team003'
          },
          {
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/team004'
    
          },
           {
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/team005'
    
          },
           {
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/team006'
    
          },
           {
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/team007'
    
          },
           {
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/team008'
    
          },
           {
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/team009'
    
          },
           {
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/team010'
    
          },
           {
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/team011'
          },
          {
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/team012'
          },
          {
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/team013'
          },
          {
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/team014'
          },
          {
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/team015'
          },
          {
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/team016'
          }
           ],
           recommendArray:[
          {
              id:0,
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/show0',
          },
          {
              id:1,
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/show001',
          },
          {
              id:2,
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/show002',
          },
          {
              id:3,
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/show003',
          },
          {
              id:4,
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/show004',
          },
          {
              id:5,
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/show005',
          },
          {
              id:6,
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/show006',
          },
          {
              id:7,
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/show007',
          },
          {
              id:8,
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/show008',
          },
          {
              id:9,
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/show009',
          },
          {
              id:10,
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/show010',
          },
          {
              id:11,
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/show011',
          },
          {
              id:12,
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/show012',
          },
          {
              id:13,
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/show013',
          },
          {
              id:14,
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/show014',
          },
          {
              id:15,
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/show015',
          },
          {
              id:17,
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/show017',
          },
          {
              id:18,
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/show018',
          },
          {
              id:19,
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/show019',
          },
          {
              id:20,
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/show020',
          },
          {
              id:21,
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/show021',
          },
          {
              id:22,
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/show022',
          },
          {
              id:23,
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/show023',
          },
          {
              id:24,
              mode:'aspectFill',
              src:'http://opgfoveg6.bkt.clouddn.com/show024',
          }
          ]
  
 }})